#!/bin/bash

rm -rf release
mkdir release
cp study touchup xgboost train.csv xglinear.conf dicom.dic run-submit.sh run-val.sh run-study.sh qsub-study.sh run-buddy.sh qsub-buddy.sh val-buddy.sh submit-buddy.sh TRAIN TRAIN1 TRAIN2 TRAIN3 README.txt release/
git describe --always > release/git-tag
cd release
git clone ../../adsb2
mv adsb2 src
cd src
git submodule init
git submodule update
find . -type d -name '.git*' -exec rm -rf {} \;
