#!/bin/bash

rm -rf release
mkdir release
cp study touchup xgboost xglinear.conf dicom.dic run-submit1.sh run-submit2.sh run-val.sh run-study.sh TRAIN TRAIN1 TRAIN2 TRAIN3 README.txt release/
cp -r data release/
cp -r val release/
cp -r pre release/
cp -r models release/models
git describe --always > release/git-tag
cd release
git clone ../../adsb2
mv adsb2 src
cd src
git submodule init
git submodule update
find . -type d -name '.git*' -exec rm -rf {} \;
